# bot settings
bot_token: "" # support bot tok                                                                                                             en
staffchat_id: "" # eg. -123456789
owner_id: ""
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private

auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server
web_server_ssl_cert: '../src/web/ssl.crt' # Path for SSL cert
web_server_ssl_key: '../src/web/ssl.key' # Path for SSL key

dev_mode: false # Enable/disable dev mode

# customize your language
language:
   startCommandText: "Добро пожаловать в наш чат поддержки! Задайте свой вопрос здесь"
   faqCommandText: "Get this bot at: <a href='https://github.com/bostrot/telegram-support-bot'>github.com</a>"
   helpCommandText: "<b>Доступные команды:</b>\n/help\n/faq\n/id"
   contactMessage: "Спасибо, что связались с нами. Мы ответим как можно скорее\n"
   blockedSpam: "Вы послали довольно много вопросов в последнее время. Пожалуйста, успокойтесь и подождите, пока персонал их проверит."
   ticket: "Запрос"
   closed: "Закрыто"
   acceptedBy: "было принято"
   dear: "Дорогой(-ая)"
   regards: "C наилучшими пожеланиями,"
   from: "от"
   language: "Язык"
   msg_sent: "Сообщение отправлено пользователю"
   file_sent: "Файл отправлен пользователю"
   usr_with_ticket: "Пользователь с запросом"
   banned: "запрещено"
   replyPrivate: "Ответ приватный"
   services: "Выберите из списка ниже"
   student: "студент"
   msgForwarding: "Ваши сообщения будут переданы поставщикам группы: "
   back: "Вернитесь назад"
   whatSubCategory: "Какая подкатегория описывает ваши вопросы лучше всего?"
   prvChatEnded: "чат окончен."
   prvChatOpened: "чат открыт"
   prvChatEnd: "Закрытый частный чат"
   prvChatOpenedCustomer: "Открытый частный чат"
   instructionsSent: "Инструкции были отправлены вам в чате"
   openTickets: "Открытый запрос"
   support: "Поддержка"
   prvChatOnly: "Эта команда может быть использована только в приватном чате"
   ticketClosed: "Ваш запрос был закрыт нашими сотрудниками. Вы можете сделать новый запрос в любое время"
   textFirst: "Пожалуйста, отправьте нам сообщение перед отправкой запроса, чтобы мы могли помочь вам лучше."
   automatedReply: "Это автоматический ответ"
   automatedReplyAuthor: "Бот"
   doesntHelp: "Это нам не поможет"
   automatedReplySent: "Автоматизированный ответ был отправлен пользователю"
   ticketReopened: "Запрос закрыт"

# categories: 
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups: 
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910" 
#  - name: "Contact"
#    msg: "Check out our Website"

    
  